### PR TITLE
Escape brackets using single quotes.

### LINKED ISSUE #182: How to escape curly brace in arb file?
I'm trying to escape the word {test} in the .arb file.

// dart file
```dart
Intl.message(
        "{test}",
        name: "flutter_test",
        args: []);
```
---
//1. intl_en.arb
```json
{
"flutter_test": "{test}",
  "@flutter_test": {
    "type": "text",
    "placeholders": {},
    "source_text": "{test}"
  },
"@@locale": "en"
}
```
Gives the error:
```
Unhandled exception:
Invalid argument(s)
#0      List.[] (dart:core-patch/growable_array.dart:145:60)
```

---
//2. intl_en.arb
```json
{
  "flutter_test": "\{test\}",
  "@flutter_test": {
    "type": "text",
    "placeholders": {},
    "source_text": "\{test\}"
  },
"@@locale": "en"
}
```
Gives the error:
```
Unhandled exception:
FormatException: Unrecognized string escape (at line 2, character 22)
  "flutter_test": "\{test\}",
                     ^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1392:5)
```
---
//3. intl_en.arb
```json
{
  "flutter_test": "\\{test\\}",
  "@flutter_test": {
    "type": "text",
    "placeholders": {},
    "source_text": "\\{test\\}"
  },
"@@locale": "nl"
}
```
Does not give a error, but shows the result \\{test\\}. ([slash][curly-brace]test[slash][curly-brace])

How to do a proper escape of a curly brace?

### PR DESCRIPTION
**Pull request by mosuem**
Fixes #182 .

### CODE REVIEW

File: lib/src/message_parser.dart [hunk 1]
```diff
@@ -180,17 +189,40 @@ class _ParserUtil {
...
+      } else {
+        matched = inputAt.substring(0, indexOf);
       }
+      return At(LiteralString(matched), at + matched.length);
     }
     return null;
   }
 
+  int indexOfUnescapedOpenBracket(String inputAt) {
+    const quote = 39; // Character '
```
Comment (devoncarew) [inline lib/src/message_parser.dart:208]: One pattern I've seen with char constants in dart is to use a `$` prefix to the name; perhaps to help call it out as a special constant? So,

```
const int $space = 0x20;
```

File: lib/src/messages/message.dart [hunk 2]
```diff
@@ -325,15 +327,37 @@ abstract class Message {
...
-    return value.splitMapJoin(
+    return escapedBrackets.splitMapJoin(
       '',
       onNonMatch: (String string) => escapes[string] ?? string,
     );
   }
 
+  static String escapeBracketsAndQuotes(String value) {
+    const quote = 39; // Character '
+    const controlCharacters = [39, 123, 125]; // Characters '{}
```
Comment (devoncarew) [inline lib/src/messages/message.dart:341]: This could then read `const controlCharacters = [$leftQuote, $leftBrace, $rightBrace]` and we wouldn't need the trailing eol comment.

File: lib/src/message_parser.dart (hunk 1 above)
Comment (devoncarew) [reply lib/src/message_parser.dart:208]: I'd move these char constants to somewhere were you can share them between here and `lib/src/messages/message.dart`.

**Review by devoncarew — APPROVED** [review]
lgtm; please do add a changelog entry before landing (and consider some refactoring around the char constants).

**Review by devoncarew — APPROVED** [review]
